version: '3'

services:
  registry-cache1:
    labels:
      traefik.http.routers.registry1.tls: 'false'
  traefik:
    environment:
      TRAEFIK_ACME_ENABLE: 'false'
      TRAEFIK_HTTPS_ENABLE: 'false'
      # use the staging server
      # TRAEFIK_ACME_CASERVER: 'https://acme-staging-v02.api.letsencrypt.org/directory'
